export const types = {
    CREATE_TASK : 'CREATE_TASK',
    GET_ALL_TODO : 'GET_ALL_TODO',
    DELETE_TODO : 'DELETE_TODO',
    EDIT_TASK : 'EDIT_TASK',
    OPEN_EDIT_TASK : 'OPEN_EDIT_TASK',
    CLOSE_EDIT_TASK : 'CLOSE_EDIT_TASK',
    UPDATE_FAVORITE_AND_COMPLETED : 'UPDATE_FAVORITE_AND_COMPLETED',
    UPDATE_MESSAGE_ON_SERVER : 'UPDATE_MESSAGE_ON_SERVER',
    SORT_BY_IMPORT : 'SORT_BY_IMPORT',
    ANIMATION_START_ASYNC : 'ANIMATION_START_ASYNC',
    //async
    ASYNC_CREATE_TASK : 'ASYNC_CREATE_TASK',
    ASYNC_GET_ALL_TODO : 'ASYNC_GET_ALL_TODO',
    ASYNC_DELETE_TODO : 'ASYNC_DELETE_TODO',
    ASYNC_UPDATE_TASK : 'ASYNC_UPDATE_TASK',
    ASYNC_OPEN_REDACTOR : 'ASYNC_OPEN_REDACTOR',
    ASYNC_UPDATE_FAVORITE_AND_COMPLETED : 'ASYNC_UPDATE_FAVORITE_AND_COMPLETED',
}